const mockAds = [
    {
        id: 1,
        title: "Apartament Modern 2 Camere",
        location: "Oradea, Nufărul",
        coordinates: { lat: 47.040, lng: 21.940 },
        price: 450,
        surface: 55,
        rooms: 2,
        floor: "2/4",
        dateTime: "24 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=400&q=80",
        user: { name: "Mihai Proprietarul", avatarUrl: "" },
        isFavorite: true,
        isActive: true
    },
    {
        id: 2,
        title: "Garsonieră Centrală",
        location: "Oradea, Ultracentral",
        coordinates: { lat: 47.058, lng: 21.932 },
        price: 280,
        surface: 32,
        rooms: 1,
        floor: "Parter",
        dateTime: "25 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=400&q=80",
        user: { name: "Mihai Proprietarul", avatarUrl: "https://i.pravatar.cc/150?u=maria" },
        isFavorite: false,
        isActive: false
    },
    {
        id: 3,
        title: "Casă curte generoasă",
        location: "Sîntandrei",
        coordinates: { lat: 47.065, lng: 21.865 },
        price: 850,
        surface: 120,
        rooms: 4,
        floor: "P+1",
        dateTime: "26 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=400&q=80",
        user: { name: "Andrei Varga", avatarUrl: "" },
        isFavorite: true,
        isActive: false
    },
    {
        id: 4,
        title: "Penthouse de lux cu vedere panoramică",
        location: "Calea Aradului",
        coordinates: { lat: 47.045, lng: 21.915 },
        price: 1200,
        surface: 150,
        rooms: 3,
        floor: "10/10",
        dateTime: "Azi",
        imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=400&q=80",
        user: { name: "Elena Popa", avatarUrl: "https://i.pravatar.cc/150?u=elena" },
        isFavorite: false,
        isActive: true
    },
    {
        id: 5,
        title: "Spațiu birouri 100mp",
        location: "Centru Civic",
        coordinates: { lat: 47.052, lng: 21.942 },
        price: 1000,
        surface: 100,
        rooms: 3,
        floor: "Etaj 1",
        dateTime: "Ieri",
        imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=400&q=80",
        user: { name: "Office Rent SRL", avatarUrl: "" },
        isFavorite: false,
        isActive: true
    },
    {
        id: 6,
        title: "Cabană munte",
        location: "Padiș",
        coordinates: { lat: 46.595, lng: 22.695 },
        price: 150,
        surface: 80,
        rooms: 3,
        floor: "Întreaga casă",
        dateTime: "Acum 2 ore",
        imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=400&q=80",
        user: { name: "Cabana Codru", avatarUrl: "" },
        isFavorite: true,
        isActive: true
    },
    {
        id: 7,
        title: "Apartament 3 camere Prima Premium",
        location: "Oradea, Decebal",
        coordinates: { lat: 47.055, lng: 21.918 },
        price: 550,
        surface: 75,
        rooms: 3,
        floor: "4/9",
        dateTime: "23 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=400&q=80",
        user: { name: "Imobiliare Vest", avatarUrl: "" },
        isFavorite: false,
        isActive: true
    },
    {
        id: 8,
        title: "Studio Cozy Rogerius",
        location: "Oradea, Rogerius",
        coordinates: { lat: 47.075, lng: 21.905 },
        price: 250,
        surface: 35,
        rooms: 1,
        floor: "8/10",
        dateTime: "22 Feb 2024",
        imageUrl: null,
        user: { name: "Vasile G.", avatarUrl: "" },
        isFavorite: true,
        isActive: false
    },
    {
        id: 9,
        title: "Casă Smart în Cartier Rezidențial",
        location: "Oradea, Grigorescu",
        coordinates: { lat: 47.085, lng: 21.955 },
        price: 1100,
        surface: 140,
        rooms: 4,
        floor: "P+M",
        dateTime: "21 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=400&q=80",
        user: { name: "Smart Homes SRL", avatarUrl: "https://i.pravatar.cc/150?u=smart" },
        isFavorite: false,
        isActive: true
    },
    {
        id: 10,
        title: "Locație centrală pentru showroom",
        location: "Oradea, Republicii",
        coordinates: { lat: 47.062, lng: 21.935 },
        price: 2000,
        surface: 120,
        rooms: 2,
        floor: "Parter",
        dateTime: "20 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1582037928769-181f2644ecb7?auto=format&fit=crop&w=400&q=80",
        user: { name: "Business Hub", avatarUrl: "" },
        isFavorite: false,
        isActive: true
    },
    {
        id: 11,
        title: "Apartament 2 camere Ioșia",
        location: "Oradea, Ioșia",
        coordinates: { lat: 47.048, lng: 21.902 },
        price: 380,
        surface: 52,
        rooms: 2,
        floor: "1/4",
        dateTime: "19 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=400&q=80",
        user: { name: "Anca Pop", avatarUrl: "https://i.pravatar.cc/150?u=anca" },
        isFavorite: true,
        isActive: true
    },
    {
        id: 12,
        title: "Hala Industrială 500mp",
        location: "Oradea, Șoseaua Borșului",
        coordinates: { lat: 47.080, lng: 21.845 },
        price: 2500,
        surface: 500,
        rooms: 5,
        floor: "Parter",
        dateTime: "18 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=400&q=80",
        user: { name: "Logistics Pro", avatarUrl: "" },
        isFavorite: false,
        isActive: true
    },
    {
        id: 13,
        title: "Apartament Lux Lotus Residence",
        location: "Oradea, Nufărul",
        coordinates: { lat: 47.038, lng: 21.948 },
        price: 600,
        surface: 65,
        rooms: 2,
        floor: "5/12",
        dateTime: "17 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=400&q=80",
        user: { name: "Cristian M.", avatarUrl: "" },
        isFavorite: false,
        isActive: true
    },
    {
        id: 14,
        title: "Garsonieră modernă mobilată",
        location: "Oradea, Cantemir",
        coordinates: { lat: 47.045, lng: 21.945 },
        price: 230,
        surface: 28,
        rooms: 1,
        floor: "3/4",
        dateTime: "16 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=400&q=80",
        user: { name: "Elena I.", avatarUrl: "" },
        isFavorite: true,
        isActive: true
    },
    {
        id: 15,
        title: "Vila cu piscină și grădină",
        location: "Sîntandrei, zona nouă",
        coordinates: { lat: 47.068, lng: 21.855 },
        price: 1800,
        surface: 250,
        rooms: 6,
        floor: "D+P+E",
        dateTime: "15 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=400&q=80",
        user: { name: "Premium Estate", avatarUrl: "" },
        isFavorite: false,
        isActive: true
    },
    {
        id: 16,
        title: "Apartament 4 camere zona semicentrală",
        location: "Oradea, Magheru",
        coordinates: { lat: 47.065, lng: 21.938 },
        price: 700,
        surface: 95,
        rooms: 4,
        floor: "2/6",
        dateTime: "14 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=400&q=80",
        user: { name: "George V.", avatarUrl: "" },
        isFavorite: false,
        isActive: true
    },
    {
        id: 17,
        title: "Spațiu comercial ultra-modern",
        location: "Oradea, Centru Civic",
        coordinates: { lat: 47.054, lng: 21.944 },
        price: 1300,
        surface: 85,
        rooms: 3,
        floor: "Parter",
        dateTime: "13 Feb 2024",
        imageUrl: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=400&q=80",
        user: { name: "City Office", avatarUrl: "https://i.pravatar.cc/150?u=city" },
        isFavorite: true,
        isActive: true
    },
    {
        id: 18,
        title: "Apartament 2 camere Velența",
        location: "Oradea, Velența",
        coordinates: { lat: 47.050, lng: 21.958 },
        price: 290,
        surface: 48,
        rooms: 2,
        floor: "4/4",
        dateTime: "12 Feb 2024",
        imageUrl: null,
        user: { name: "Sandu P.", avatarUrl: "" },
        isFavorite: false,
        isActive: false
    }
];

export default mockAds;